export const CONNECTION_STATE = {
  DISCONNECTED: 'DISCONNECTED',
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED',
};

export const MODE = {
  PROXY_URL: 'PROXY_URL',
  FIXED_RESPONSE: 'FIXED_RESPONSE',
};
